name: test
on:
  workflow_dispatch:

defaults:
  run:
    shell: bash

jobs:
  build:
    runs-on: macos-13
    steps:
      - name: ✅ -march=native
        run: clang -march=native -dM -E - </dev/null

      - name: ✅ -arch arm64
        run: clang -arch arm64 -dM -E - </dev/null

      - name: ❌ -march=native --target=arm64-apple-ios16.0
        if: ${{ success() || failure() }}
        run: clang -isysroot $(xcrun --sdk iphoneos --show-sdk-path) -march=native --target=arm64-apple-ios16.0 -dM -E - </dev/null
      
      - name: ❌ -march=native -arch arm64
        if: ${{ success() || failure() }}
        run: clang -march=native -arch arm64 -dM -E - </dev/null
        
