name: test
on:
  workflow_dispatch:

defaults:
  run:
    shell: bash

jobs:
  build:
    runs-on: macos-13
    steps:
      - name: ✅ Detecting CPU architecture compile-time
        run: clang -march=native -dM -E - </dev/null

      - name: ✅ Detecting CPU architecture compile-time
        run: clang -arch arm64 -dM -E - </dev/null
      
      - name: ❌ Detecting CPU architecture compile-time
        run: clang -march=native -arch arm64 -dM -E - </dev/null
        

